# Generated by Django 4.1.7 on 2023-03-17 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='name',
        ),
        migrations.AddField(
            model_name='health',
            name='height',
            field=models.FloatField(default=0.1, max_length=4),
            preserve_default=False,
        ),
    ]
