# Generated by Django 4.1.7 on 2023-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0002_remove_health_name_health_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.FloatField(),
        ),
    ]
