# Generated by Django 4.1.7 on 2023-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_alter_health_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.FloatField(default=1.0),
        ),
    ]
