# Generated by Django 4.1.7 on 2023-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0004_alter_health_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.FloatField(max_length=5),
        ),
    ]
