# Generated by Django 4.1.7 on 2023-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0005_alter_health_height_alter_health_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.FloatField(help_text='In meters', max_length=5),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.FloatField(help_text='In kilograms', max_length=5),
        ),
    ]
