# Generated by Django 4.1.7 on 2023-03-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0007_dailymeal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMeal',
            new_name='Meal',
        ),
    ]
