# Generated by Django 4.1.7 on 2023-03-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0008_rename_dailymeal_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health',
        ),
    ]
